FROM selenium/node-chrome:4.0.0-beta-1-20210215 as selenium
LABEL authors=SeleniumHQ

USER 1200

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY start-selenium-standalone.sh /opt/bin/start-selenium-standalone.sh

#==============================
# Supervisor configuration file
#==============================
COPY selenium.conf /etc/supervisor/conf.d/

EXPOSE 4444

# Base image
FROM python:3.8

# Working directory
WORKDIR /CatchTheWave
ENV PATH="/usr/bin/chromedriver:${PATH}" 


# Copy dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy content of the local src directory to the working directory
COPY data/ data/
COPY plots/ plots/
COPY src/ src/

# Command to run on container start
RUN [ "python", "./src/stocks__evaluation.py" ]
